# Generated by Django 4.1.1 on 2022-09-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_airport_alter_flight_destination_alter_flight_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='t_id',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
