# Generated by Django 4.1.1 on 2022-09-25 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_flight_t_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='t_id',
        ),
    ]
