# Generated by Django 4.1.1 on 2022-09-27 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0007_passengers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Passengers',
            new_name='Passenger',
        ),
    ]
